import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <nav className="flex flex-wrap items-center gap-6 p-6 bg-white border-b border-gray-200 sticky top-0 z-50">
          <Link href="/" className="font-bold text-xl mr-4">Brand</Link>
          <Link href="/about" className="hover:text-blue-600 transition">About</Link>
          <Link href="/services" className="hover:text-blue-600 transition">Services</Link>
          <Link href="/products" className="hover:text-blue-600 transition">Products</Link>
          <Link href="/blogs" className="hover:text-blue-600 transition">Blogs</Link>
          <Link href="/contact" className="hover:text-blue-600 transition">Contact</Link>  
          <div className="ml-auto flex items-center gap-4">
            <Link href="/user/order-history" className="text-sm text-gray-600 hover:text-black">Orders</Link>
            <Link href="/user/wishlist-history" className="text-sm text-gray-600 hover:text-black">Wishlist</Link>
            <Link href="/auth/registration" className="text-sm text-gray-600 hover:text-black">Sign Up</Link>
            <Link href="/auth/login" className="px-5 py-2 bg-black text-white rounded-full text-sm font-medium hover:bg-gray-800 transition">
              Login
            </Link>
          </div>
        </nav>
        <main className="max-w-7xl mx-auto p-6">
          {children}
        </main>
      </body>
    </html>
  );
}